asset_classes:
  crypto:
    exchanges:
    - binance
    - coinbase
    - kraken
    min_market_cap: 1000000000
    trading_hours:
      end: '23:59'
      start: 00:00
      timezone: UTC
  forex:
    major_pairs:
    - EUR/USD
    - GBP/USD
    - USD/JPY
    - USD/CHF
    trading_hours:
      end: '17:00'
      start: '17:00'
      timezone: US/Eastern
  stocks:
    max_price: 1000.0
    min_price: 5.0
    min_volume: 100000
    trading_hours:
      end: '16:00'
      start: 09:30
      timezone: US/Eastern
backtesting:
  benchmark: SPY
  default_end_date: '2024-12-31'
  default_start_date: '2020-01-01'
  initial_capital: 100000
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  - calmar_ratio
global_settings:
  correlation_threshold: 0.7
  data_requirements:
    min_history_days: 252
    required_indicators:
    - sma
    - ema
    - rsi
    - bollinger
    - volume
    required_timeframes:
    - 1m
    - 5m
    - 1h
    - 1d
  execution:
    commission_rate: 0.001
    market_impact_factor: 0.0001
    order_timeout: 30
    slippage_model: linear
  max_concurrent_positions: 5
  portfolio_heat: 0.1
  risk_management:
    max_daily_loss: 0.05
    max_drawdown: 0.2
    position_sizing_method: fixed_fractional
strategies:
  bollinger_bands:
    description: Bollinger Bands breakout/reversion strategy
    enabled: true
    parameters:
      asset_classes:
      - stocks
      - forex
      mode: breakout
      period: 20
      risk_per_trade: 0.02
      std_dev: 2
      stop_loss_pct: 0.04
      symbols:
      - AAPL
      - MSFT
      - GOOGL
      - TSLA
      - NVDA
      take_profit_pct: 0.08
    type: conventional
  ma_crossover:
    description: Simple moving average crossover strategy
    enabled: true
    parameters:
      asset_classes:
      - stocks
      - forex
      - crypto
      fast_period: 10
      risk_per_trade: 0.02
      slow_period: 30
      stop_loss_pct: 0.05
      symbols:
      - AAPL
      - MSFT
      - GOOGL
      - TSLA
      - NVDA
      take_profit_pct: 0.1
    type: conventional
  rsi_mean_reversion:
    description: RSI-based mean reversion strategy
    enabled: false
    parameters:
      asset_classes:
      - stocks
      overbought_threshold: 70
      oversold_threshold: 30
      risk_per_trade: 0.015
      rsi_period: 14
      stop_loss_pct: 0.03
      symbols:
      - AAPL
      - MSFT
      - GOOGL
      - TSLA
      - NVDA
      take_profit_pct: 0.06
    type: conventional
