asset_class_limits:
  commodities:
    max_allocation: 0.2
  crypto:
    max_allocation: 0.05
  forex:
    max_allocation: 0.25
  futures:
    max_allocation: 0.1
  stocks:
    max_allocation: 0.4
global_settings:
  correlation_threshold: 0.7
  execution:
    commission_rates:
      crypto: 0.001
      forex: 2.5e-05
      futures: 2.5
      options: 1.0
      stocks: 0.005
    slippage_model: adaptive
  max_concurrent_positions: 10
  portfolio_heat: 0.15
  risk_management:
    max_daily_loss: 0.05
    max_drawdown: 0.2
    position_sizing_method: volatility_adjusted
strategies:
  commodity_seasonality:
    description: Commodity seasonality strategy
    enabled: true
    parameters:
      markets:
        commodities:
        - ZC
        - ZS
        - ZW
        - NG
        - CL
      risk_per_trade: 0.025
      seasonal_patterns: true
      storage_cost_factor: true
    type: conventional
  forex_carry_trade:
    description: Forex carry trade strategy
    enabled: true
    parameters:
      hold_period_days: 30
      interest_rate_threshold: 0.02
      markets:
        forex:
        - AUD.USD
        - NZD.USD
        - USD.JPY
        - EUR.USD
      risk_per_trade: 0.015
    type: conventional
  multi_market_momentum:
    description: Momentum strategy across all asset classes
    enabled: true
    parameters:
      lookback_period: 20
      markets:
        commodities:
        - GC
        - CL
        - NG
        forex:
        - EUR.USD
        - GBP.USD
        - USD.JPY
        futures:
        - ES
        - NQ
        stocks:
        - AAPL
        - MSFT
        - GOOGL
        - TSLA
        - SPY
      momentum_threshold: 0.02
      risk_per_trade: 0.02
      stop_loss_pct: 0.05
      take_profit_pct: 0.1
    type: conventional
